<?xml version="1.0"?>
<robot>

<!-- Null inertia macro. -->
    <macro name="null_inertial">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.001"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </macro>

<!-- Cylinder inertia macro. -->
    <macro name="cylinder_inertia" params="m r h">
        <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}" />
    </macro>

<!-- Box inertia macro. -->
    <macro name="box_inertia" params="m x y z">
        <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0" iyy="${m*(x*x+z*z)/12}" iyz = "0" izz="${m*(x*x+z*z)/12}" />
    </macro>

<!-- Sphere inertia macro. -->
    <macro name="sphere_inertia" params="m r">
        <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0" iyy="${2*m*r*r/5}" iyz = "0" izz="${2*m*r*r/5}" />
    </macro>

<!-- Axle macro. -->
    <macro name="axle" params="fr_prefix fr_position">
        <link name="${fr_prefix}_axle">
            <collision>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
                <geometry>
                    <cylinder length="${axle_length}" radius="${axle_radius}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
                <geometry>
                    <cylinder length="${axle_length}" radius="${axle_radius}"/>
                </geometry>
                <material name="black"/>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
                <mass value="${wheelMass}"/>
                <cylinder_inertia m="${axle_mass}" r="${axle_radius}" h="${axle_length}"/>
            </inertial>
        </link>

        <joint name="${fr_prefix}_axle_joint" type="fixed">
            <origin xyz="${fr_position * chassisLength / 2} 0 ${wheelRadius + chassisHeight/2}" rpy="0 0 0" />
            <parent link="chassis"/>
            <child link="${fr_prefix}_axle"/>
        </joint>
    </macro>

<!-- Wheel Macro. -->
    <macro name="wheel" params="fr_prefix lr_prefix tX tY fr_axle fr_axle_position axle_eff_limit">
        <!-- Params: front-back left-right translationX translationY -->

        <link name="${fr_prefix}_${lr_prefix}_wheel">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 ${PI/2}" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
                <material name="black"/>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
                <mass value="${wheelMass}"/>
                <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
            </inertial>

            <max_contacts>1</max_contacts>

            <surface>
                <contact>
                    <ode>
                        <soft_cfm>0.000000001</soft_cfm>
                        <soft_erp>0.2</soft_erp>
                        <kp>1e+10</kp>
                        <kd>10</kd>
                        <max_vel>0.01</max_vel>
                        <min_depth>0.005</min_depth>
                    </ode>
                </contact>
            </surface>
        </link>

        <gazebo reference="${fr_prefix}_${lr_prefix}_wheel">
            <!-- Define friction of the wheel. -->
            <mu1>0.7</mu1>
            <mu2>0.75</mu2>

            <material>Gazebo/Black</material>
        </gazebo>
    </macro>

<!-- Front wheel macro. -->
    <macro name="front_wheel"
            params="lr_prefix fr_prefix lr_position fr_position wheel_radius wheel_mass axle_eff_limit">

            <link name="${fr_prefix}_${lr_prefix}_steering_link">
                <null_inertial/>
            </link>

            <!-- Add the steering_link to the axle. -->
            <joint name="${fr_prefix}_${lr_prefix}_steering_to_chassis_joint" type="fixed">
                <parent link="${fr_prefix}_axle"/>
                <child link="${fr_prefix}_${lr_prefix}_steering_link"/>

                <origin xyz="0 ${lr_position*(axle_length/2)} 0" rpy="0 0 0" />
            </joint>

            <!-- Add wheel carrier. -->
            <link name="${fr_prefix}_${lr_prefix}_wheel_carrier">
                <null_inertial />
            </link>

            <!-- Add the joint for steering. -->
            <joint name="${fr_prefix}_${lr_prefix}_steering_joint" type="revolute">
                <origin xyz="0 0 0" rpy="0 0 0" />
                <parent link="${fr_prefix}_${lr_prefix}_steering_link"/>
                <child link="${fr_prefix}_${lr_prefix}_wheel_carrier" />

                <!-- cant the front wheels to improve traction -->
                <axis xyz="0 ${-lr_position * 0.09950372}  0.99503719"/>
                <limit  lower="0" upper="0"
                        effort="${servo_stall_torque}" velocity="${servo_no_load_speed}"/>
            </joint>   

            <transmission name="${lr_prefix}_steering_trans">
                <type>transmission_interface/SimpleTransmission</type>

                <joint name="${fr_prefix}_${lr_prefix}_steering_joint">
                    <hardwareInterface>EffortJointInterface</hardwareInterface>
                </joint>

                <actuator name="${lr_prefix}_steering_act">
                    <hardwareInterface>EffortJointInterface</hardwareInterface>
                    <mechanicalReduction>1</mechanicalReduction>
                </actuator>
            </transmission> 

            <!-- Add the wheel. -->
            <wheel  fr_prefix="${fr_prefix}"
                    lr_prefix="${lr_prefix}" 
                    tX="${fr_position}" 
                    tY="${lr_position}" 
                    fr_axle="${fr_prefix}" 
                    fr_axle_position="${fr_position}"
                    axle_eff_limit="${axle_eff_limit}"
            />

            <!-- Add the wheel joint. -->
            <joint name="${fr_prefix}_${lr_prefix}_wheel_joint" type="continuous">
                <parent link="${fr_prefix}_${lr_prefix}_wheel_carrier" />
                <child link="${fr_prefix}_${lr_prefix}_wheel"/>
                <origin xyz="0 ${lr_position*(wheelWidth/2)} 0" ryp="0 0 0" />
                
                <axis xyz="0 1 0" rpy="0 0 0" />
                <limit effort="${axle_eff_limit}" velocity="${axle_vel_limit}"/>
                <dynamics damping="0.001" friction="0.5"/>
            </joint>

            <transmission name="${fr_prefix}_${lr_prefix}_trans">
                <type>transmission_interface/SimpleTransmission</type>

                <joint name="${fr_prefix}_${lr_prefix}_wheel_joint">
                    <hardwareInterface>EffortJointInterface</hardwareInterface>
                </joint>

                <actuator name="${fr_prefix}_${lr_prefix}_axle_act">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
                </actuator>
            </transmission>
    </macro> 

<!-- Rear wheel -->
    <macro  name="rear_wheel"
            params="lr_prefix fr_prefix lr_position fr_position wheel_radius wheel_mass axle_eff_limit">

        <!-- Add the wheel. -->
        <wheel  fr_prefix="${fr_prefix}"
                lr_prefix="${lr_prefix}" 
                tX="${fr_position}" 
                tY="${lr_position}" 
                fr_axle="${fr_prefix}" 
                fr_axle_position="${fr_position}"
                axle_eff_limit="${axle_eff_limit}"
        />

        <joint name="${fr_prefix}_${lr_prefix}_wheel_axle" type="continuous">
            <parent link="${fr_prefix}_axle"/>
            <child link="${fr_prefix}_${lr_prefix}_wheel"/>
            <origin xyz="0 ${lr_position*(axle_length/2) + lr_position*(wheelWidth/2)} 0" ryp="0 0 0" />
            <!-- Add -0.01 to align the wheels. -->
            <axis xyz="0 1 0" rpy="0 0 0" />
            <limit effort="${axle_eff_limit}" velocity="${axle_vel_limit}"/>
            <dynamics damping="0.001" friction="0.5"/>
        </joint>

        <transmission name="${fr_prefix}_${lr_prefix}_trans">
            <type>transmission_interface/SimpleTransmission</type>

            <joint name="${fr_prefix}_${lr_prefix}_wheel_axle">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>

            <actuator name="${fr_prefix}_${lr_prefix}_axle_act">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </macro>

</robot>