<?xml version="1.0"?>
<robot name="tas_car" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- CAR DESCRIPTION -->

        <!-- Physical properties. -->
        <xacro:property name="PI" value="3.1415926535897931"/>

        <!-- Chassis. -->
		<xacro:property name="chassisLength" value="0.358"/>
		<xacro:property name="chassisWidth" value="0.18"/>
		<xacro:property name="chassisHeight" value="0.068"/> <!-- Almin: 0.138 -->
		<xacro:property name="chassisMass" value="3"/>

		<!-- Caster. -->
		<xacro:property name="casterRadius" value="0.05"/>
		<xacro:property name="casterMass" value="5"/>

		<!-- Wheels. -->
		<xacro:property name="wheelWidth" value="0.059"/>
		<xacro:property name="wheelRadius" value="0.0695"/>
		<xacro:property name="wheelPos" value="0.179"/>
		<xacro:property name="wheelMass" value="0.5"/>

		<xacro:property name="wheelOffsetX" value="0.179" />
		<xacro:property name="wheelOffsetY" value="0.1815" />

		<!-- Camera. -->
		<xacro:property name="cameraSize" value="0.05"/>
		<xacro:property name="cameraMass" value="0.1"/>


        <!-- Include files. -->
		<xacro:include filename="$(find tas_car_description)/urdf/tas_car.gazebo" />
		<xacro:include filename="$(find tas_car_description)/urdf/materials.xacro" />
		<xacro:include filename="$(find tas_car_description)/urdf/macros.xacro" />

		<!-- Robot description. -->

		<!-- The physics engine does not accept a base_link with inertia. Add a simple link without inertia and make a joint between it and the chassis. -->
		<link name="footprint" />

		<joint name="base_joint" type="fixed">
			<parent link="footprint"/>
			<child link="chassis"/>
		</joint>

		<link name="chassis">
			<collision>
				<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
			    <geometry> 
			      <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
			    </geometry> 
			</collision>

			<visual>
				<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
			    <geometry> 
			    	<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
			    </geometry> 
			    <material name="orange"/>
			</visual>

			<inertial>
				<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      			<mass value="${chassisMass}"/>
      			<box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
			</inertial>
		</link>

		<wheel fb="front" lr="left" tX="1" tY="1" />
		<wheel fb="front" lr="right" tX="1" tY="-1" />

		<backwheel fb="back" lr="left" tX="-1" tY="1" />
		<backwheel fb="back" lr="right" tX="-1" tY="-1" />

	<!-- CAR DESCRIPTION END -->

	<!-- SENSORS -->

		<!-- Camera. -->
	<!--
		<joint name="camera_joint" type="fixed">
			<origin xyz="${-cameraSize+chassisLength/2} 0 ${cameraSize+wheelRadius+cameraSize/2}" rpy="0 0 0"/>
			<parent link="chassis"/>
			<child link="camera"/>
		</joint>

		<link name="camera">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
				</geometry>
			</collision>

			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
				</geometry>
				<material name="blue"/>
			</visual>

			<inertial>
				<mass value="${cameraMass}" />
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
			</inertial>
		</link>
	-->

		<!-- Laser Scanner. -->
		<joint name="hokuyo_joint" type="fixed">
			<axis xyz="0 1 0" />
			<origin xyz="${-cameraSize+chassisLength/2} 0 ${cameraSize+wheelRadius}" rpy="0 0 0"/>
			<parent link="chassis"/>
			<child link="hokuyo_link"/>
		</joint>

		<!-- Hokuyo Laser -->
		<link name="hokuyo_link">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<box size="0.1 0.1 0.1"/>
				</geometry>
			</collision>

			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find tas_car_description)/meshes/hokuyo.dae"/>
				</geometry>
			</visual>

			<inertial>
				<mass value="1e-5" />
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
			</inertial>
		</link>
	<!-- SENSOR END -->
</robot>